T: 1000
T_eval: 20
T_sampler: uniform
accum_batches: 1
autoenc_mid_attn: true
base_dir: checkpoints
batch_size: 8
batch_size_eval: 8
beatgans_rescale_timesteps: false
beta_scheduler: linear
continue_from: null
contrast: true
data_cache_dir: /home/aijishak/cache
data_name: BrainAge
data_val_name: ''
diffusion_type: beatgans
dropout: 0.1
ema_decay: 0.9999
eval_ema_every_samples: 10000000
eval_every_samples: 10000000
eval_num_images: 5000
eval_path: null
eval_programs: null
fid_use_torch: true
fp16: true
from_ckpt: true
grad_clip: 1
img_size: 128
latent_T_eval: 1000
latent_beta_scheduler: linear
latent_clip_sample: false
latent_infer_path: null
latent_rescale_timesteps: false
latent_znormalize: false
lr: 0.0001
manipulate_cls: null
manipulate_seed: 0
manipulate_shots: null
manipulate_znormalize: false
model_conf:
  attention_resolutions: &id001 !!python/tuple
  - 16
  attn_checkpoint: false
  channel_mult: &id002 !!python/tuple
  - 1
  - 1
  - 2
  - 3
  - 4
  conv_resample: true
  dims: 2
  dropout: 0.1
  embed_channels: 512
  enc_attn_resolutions: null
  enc_channel_mult: &id003 !!python/tuple
  - 1
  - 2
  - 3
  - 4
  enc_grad_checkpoint: false
  enc_num_res_block: 2
  enc_out_channels: 512
  enc_pool: adaptivenonzero
  image_size: 128
  in_channels: 1
  input_channel_mult: null
  latent_net_conf: null
  model_channels: 32
  num_classes: null
  num_head_channels: -1
  num_heads: 1
  num_heads_upsample: -1
  num_input_res_blocks: null
  num_res_blocks: 2
  out_channels: 1
  resblock_updown: true
  resnet_cond_channels: null
  resnet_two_cond: true
  resnet_use_zero_module: true
  time_embed_channels: null
  use_checkpoint: false
  use_new_attention_order: false
name: Example_Diffusion_Model
net_attn: *id001
net_autoenc_stochastic: false
net_beatgans_attn_head: 1
net_beatgans_embed_channels: 512
net_beatgans_gradient_checkpoint: false
net_beatgans_resnet_cond_channels: null
net_beatgans_resnet_two_cond: true
net_beatgans_resnet_use_zero_module: true
net_ch: 32
net_ch_mult: *id002
net_enc_attn: null
net_enc_channel_mult: *id003
net_enc_grad_checkpoint: false
net_enc_k: null
net_enc_num_cls: null
net_enc_num_res_blocks: 2
net_enc_pool: adaptivenonzero
net_enc_use_time: false
net_latent_channel_mult: !!python/tuple
- 1
- 2
- 4
net_latent_condition_bias: 0
net_latent_dropout: 0
net_latent_layers: null
net_latent_num_hid_channels: 1024
net_latent_num_time_layers: 2
net_latent_skip_layers: null
net_latent_time_emb_channels: 64
net_latent_time_last_act: false
net_latent_use_norm: false
net_num_input_res_blocks: null
net_num_res_blocks: 2
net_resblock_updown: true
num_workers: 4
parallel: false
postfix: ''
pretrain: null
sample_every_samples: 20000
sample_size: 32
save_every_samples: 100000
seed: 0
style_ch: 512
total_samples: 130000000
train_cond0_prob: 0
train_interpolate_img: false
train_interpolate_prob: 0
train_pred_xstart_detach: true
use_cache_dataset: false
warmup: 0
weight_decay: 0
work_cache_dir: /home/aijishak/mycache
